execute pathogen#infect()
syntax on
filetype plugin indent on

map <C-e> :NERDTreeToggle<CR>

set showcmd
set encoding=utf-8
set incsearch
set pastetoggle=<F2>
set showmode
set tabstop=4
set shiftwidth=4
set expandtab

" vim-multi-cursor config
let g:multi_cursor_use_default_mapping=0
let g:multi_cursor_start_key='<C-d>'
let g:multi_cursor_start_word_key='g<C-d>'
let g:multi_cursor_next_key='<C-d>'
let g:multi_cursor_prev_key='<C-f>'
let g:multi_cursor_skip_key='<C-x>'
let g:multi_cursor_quit_key='<Esc>'

" molokai-color
let g:molokai_original = 1
let g:rehash256 = 1

autocmd InsertLeave * se nocul  
autocmd InsertEnter * se cul

au BufReadPost * if line("'\"") > 0|if line("'\"") <= line("$")|exe("norm '\"")|else|exe "norm $"|endif|endif
